### ISSUE TITLE
multiply_drops effect not working

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoItems#10]
**Describe the bug**
When trying to make a pickaxe double the drops by 2 it will always drop 1

**To Reproduce**
1. Grab a pickaxe with this configs of effects:
```
  - id: multiply_drops
    args:
      fortune: 3
      on_items: 20
    triggers:
    - block_item_drop
```

2. Mine a block / kill a mob
3. it won't change anything

**Expected behavior**
it should double / triple or idk how many since I've put a ridiculous number as a test run

**Screenshots**
None

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
Eco: 6.20.4
EcoSkills: 3.17.3
**Additional context**
none
