### ISSUE TITLE
Cooldown feature and multiply_stat Effect not working

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoItems#4]
Hello the cooldown feature is not working, after testing it I don't have any messages and and the cooldown isn't being applied (no errors)
````
weapons:
  - id: rogue_zweihander
    baseDamage: 8
    baseAttackSpeed: 1.6
    effects:
      - id: attack_speed_multiplier
        args:
          multiplier: 1.5
      - id: give_money  
        args:
          amount: 1
          chance: 100
          cooldown: 100
        triggers: 
          - kill   
        filters:
          entities:
            - cow  
````

For the multiply_stat is simply not working; 
```
      - id: multiply_stat
        args:
          stat: strength
          multiplier: 10
```
