### ISSUE TITLE
Run_command and Run_player_command dont work

### ISSUE THREAD

**Issue by iSeitan** [Auxilor/EcoItems#54]
We tested different item, different command but we cant make it work
heres our config

- id: parapluie
  baseDamage: 1
  baseAttackSpeed: 1
  effect:
    - id: run_command
      args:
        command: pweather %player% sun
      triggers:
        - toggle_sneak
  conditions: []
  fuels: []
  item:
    item: iron_pickaxe unbreaking:1 hide_enchants hide_attributes
    displayName: '&aParapluie'
    lore:
    - '&fTrès utile pour ne plus voir'
    - '&fLa pluie'
    - ''
    - '&7Rareté: &9Commun'
    craftable: true
    recipe:
    - leather:64
    - iron_ingot:64
    - leather:64
    - leather:64
    - iron_ingot:64
    - leather:64
    - ''
    - iron_ingot:64
    - ''

**Comment by Sedri05** [comment]
Does work just tested it
here is what i used
```
  effects:
    - id: run_player_command
      args:
        command: "say hello %player%"
        as_op: true
      triggers:
      - alt_click
```
