### ISSUE TITLE
Recipes with items from ecoarmor (or any other ecoplugin) wont work untill reload

### ISSUE THREAD

**Issue by Sedri05** [Auxilor/EcoItems#67]
**Describe the bug**
When creating a recipe with a ecoarmor result the recipe wont load untill you reload ecoitems. It will also say that the recipe will of air which isnt true.

**To Reproduce**
1. create a ecoamor set
2. make a new recipe for it
in this case i used:
```
  - result: ecoarmor:set_diamond_replacement_leggings
    recipeGiveAmount: 1
    recipe:
      - leather
      - leather
      - leather
      - leather
      - air 
      - leather
      - leather
      - air
      - leather
```
3. restart

**Expected behavior**
Well it should just load the recipe ofcourse
