### ISSUE TITLE
Points system auto regenerate

### ISSUE THREAD

**Issue by PQguanfang** [Auxilor/EcoItems#71]
**Is your feature request related to a problem? Please describe.**
A good example for points system is mana, however, its impossible for EcoItems or EcoSkills to make points auto regenerate which it should be.
In most games or Minecraft servers, when players is not try attack others or be damaged, the mana should auto regenerate until it reach the max value, instead of need hold a weapon or use a consume.
So, please add a feature that allow users config points auto regenerate, like a permanent effect:
```
- id: regenerate_points
  args:
    type: g_souls # The point to add/subtract
    amount_per_tick: 0.1 # The value that the point auto regenerate per tick
    only_peaceful_active: true # The effect will only be actived when players not try attack others or be damaged
```
or
add 3 conditions:
```
- id: is_attacking
```
```
- id: is_being_damaged
```
```
- id: none_of # Like any_of, but this should when all conditions not meet, the effect will actived.
```
then we can use `static_<time>` trigger with the 3 conditions also make this feature.

Thanks.
